/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Discover.Game.Casillas.Tarjetas;

import Discover.Game.Casillas.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dany
 */
public class TipoTarjeta extends javax.swing.JDialog {

    /**
     * Creates new form TipoCasilla
     */
       /**
     * crea un dialogo 
     * @param parent resive un parametro de tipo frame
     * @param modal recibe un boolean
     */
    public TipoTarjeta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/img/iconoDiscover1.png")).getImage();
        setIconImage(icon);

        jLabelMensaje.setVisible(true);

        jLabelCantidadCasillas.setVisible(false);
        txtCantidadCasillas.setVisible(false);
        jLabelCantidadMulta.setVisible(false);
        jLabelCantidadPremio.setVisible(false);
        txtCantidadMulta.setVisible(false);
        txtCantidadPremio.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTipo = new javax.swing.JLabel();
        tipoTarjeta = new javax.swing.JComboBox<>();
        botonHecho = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadCasillas = new javax.swing.JTextField();
        jLabelCantidadCasillas = new javax.swing.JLabel();
        txtCantidadMulta = new javax.swing.JTextField();
        jLabelCantidadPremio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensaje = new javax.swing.JTextArea();
        txtCantidadPremio = new javax.swing.JTextField();
        jLabelCantidadMulta = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoDiscover1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo Tarjeta - Discover");

        jPanel2.setBackground(new java.awt.Color(227, 0, 38));

        jLabelTipo.setForeground(java.awt.Color.white);
        jLabelTipo.setText("Tipo");

        tipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Caminar", "Premio", "Multa", "Pago a jugadores", "Mover a casilla", "Perder turno", "Salga de la cárcel", "Vaya a la cárcel", "Personalizada" }));
        tipoTarjeta.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                tipoTarjetaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        tipoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoTarjetaActionPerformed(evt);
            }
        });

        botonHecho.setText("Hecho");
        botonHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHechoActionPerformed(evt);
            }
        });

        jLabelMensaje.setForeground(java.awt.Color.white);
        jLabelMensaje.setText("Mensaje");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoDiscover1.png"))); // NOI18N

        txtCantidadCasillas.setText("7");
        txtCantidadCasillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadCasillasActionPerformed(evt);
            }
        });
        txtCantidadCasillas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCantidadCasillasPropertyChange(evt);
            }
        });
        txtCantidadCasillas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadCasillasKeyPressed(evt);
            }
        });

        jLabelCantidadCasillas.setForeground(java.awt.Color.white);
        jLabelCantidadCasillas.setText("Cantidad Casillas");

        txtCantidadMulta.setText("50");
        txtCantidadMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadMultaActionPerformed(evt);
            }
        });
        txtCantidadMulta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCantidadMultaPropertyChange(evt);
            }
        });
        txtCantidadMulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadMultaKeyPressed(evt);
            }
        });

        jLabelCantidadPremio.setForeground(java.awt.Color.white);
        jLabelCantidadPremio.setText("Cantidad Premio");

        jTextAreaMensaje.setColumns(20);
        jTextAreaMensaje.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMensaje);

        txtCantidadPremio.setText("50");
        txtCantidadPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadPremioActionPerformed(evt);
            }
        });
        txtCantidadPremio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCantidadPremioPropertyChange(evt);
            }
        });
        txtCantidadPremio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadPremioKeyPressed(evt);
            }
        });

        jLabelCantidadMulta.setForeground(java.awt.Color.white);
        jLabelCantidadMulta.setText("Cantidad Pagar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabelCantidadCasillas)
                                .addComponent(jLabelMensaje)
                                .addComponent(tipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelTipo)
                                .addComponent(jLabelCantidadPremio)
                                .addComponent(jLabelCantidadMulta))
                            .addComponent(botonHecho, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadPremio)
                            .addComponent(txtCantidadMulta)
                            .addComponent(txtCantidadCasillas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCantidadCasillas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadCasillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCantidadPremio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidadPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCantidadMulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonHecho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static int tipo, cantidadCopias,cantiadadCasillas,cantidadMulta,cantidadPremio;
    static String nombre, mensaje;

    public static int getTipo() {
        return tipo;
    }

    public static void setTipo(int tipo) {
        TipoTarjeta.tipo = tipo;
    }

    public static String getNombre() {
        return nombre;
    }

    public static void setNombre(String nombre) {
        TipoTarjeta.nombre = nombre;
    }

     public static int getCantidadCopias() {
        return cantidadCopias;
    }

    public static void setCantidadCopias(int cantidadCopias) {
        TipoTarjeta.cantidadCopias = cantidadCopias;
    }

    public static String getMensaje() {
        return mensaje;
    }

    public static void setMensaje(String mensaje) {
        TipoTarjeta.mensaje = mensaje;
    }
    
    
   

    public static int getCantiadadCasillas() {
        return cantiadadCasillas;
    }

    public static void setCantiadadCasillas(int cantiadadCasillas) {
        TipoTarjeta.cantiadadCasillas = cantiadadCasillas;
    }

    public static int getCantidadMulta() {
        return cantidadMulta;
    }

    public static void setCantidadMulta(int cantidadMulta) {
        TipoTarjeta.cantidadMulta = cantidadMulta;
    }

    public static int getCantidadPremio() {
        return cantidadPremio;
    }

    public static void setCantidadPremio(int cantidadPremio) {
        TipoTarjeta.cantidadPremio = cantidadPremio;
        
    }
    
    
    /**
     * @param evt agrega a las variables lo que el usuario escribio en los
     * campos
     */
    private void botonHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHechoActionPerformed

        setMensaje(jTextAreaMensaje.getText());
        setCantiadadCasillas(Integer.parseInt(txtCantidadCasillas.getText()));
        setCantidadMulta(Integer.parseInt(txtCantidadMulta.getText()));
        setCantidadPremio(Integer.parseInt(txtCantidadPremio.getText()));
        JOptionPane.showMessageDialog(this, "Agregado con Exito");
        dispose();
    }//GEN-LAST:event_botonHechoActionPerformed

    private void tipoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoTarjetaActionPerformed
    /**
     * llama al metodo agregar
     *
     * @param evt
     */
    private void tipoTarjetaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_tipoTarjetaPopupMenuWillBecomeInvisible
        agregar();
    }//GEN-LAST:event_tipoTarjetaPopupMenuWillBecomeInvisible

    private void txtCantidadMultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadMultaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMultaKeyPressed

    private void txtCantidadMultaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCantidadMultaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMultaPropertyChange

    private void txtCantidadMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMultaActionPerformed

    private void txtCantidadCasillasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadCasillasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCasillasKeyPressed

    private void txtCantidadCasillasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCantidadCasillasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCasillasPropertyChange

    private void txtCantidadCasillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadCasillasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCasillasActionPerformed

    private void txtCantidadPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadPremioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadPremioActionPerformed

    private void txtCantidadPremioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCantidadPremioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadPremioPropertyChange

    private void txtCantidadPremioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadPremioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadPremioKeyPressed

    /**
     * agrega muestra las opciones para una casilla dependiendo de lo que se
     * sellecione en el jcombobox
     */
    public void agregar() {
        /*
Seleccione el tipo
Caminar
Premio
Multa
Pago a jugadores
Mover a casilla
Perder turno
Salga de la cárcel
Vaya a la cárcel
Personalizada
         */

        if (tipoTarjeta.getSelectedItem() == "Caminar") {
            tipo = 0;
            jLabelCantidadCasillas.setVisible(true);
            txtCantidadCasillas.setVisible(true);
        }
        if (tipoTarjeta.getSelectedItem() == "Premio") {
            tipo = 1;
            jLabelCantidadPremio.setVisible(true);
            txtCantidadPremio.setVisible(true);
        }
        if (tipoTarjeta.getSelectedItem() == "Multa") {
            tipo = 2;
            jLabelCantidadMulta.setVisible(true);
            txtCantidadMulta.setVisible(true);
        }
        if (tipoTarjeta.getSelectedItem() == "Pago a jugadores") {
            tipo = 3;
            jLabelCantidadMulta.setVisible(true);
            txtCantidadMulta.setVisible(true);
        }
        if (tipoTarjeta.getSelectedItem() == "Mover a casilla") {
            tipo = 4;

        }
        if (tipoTarjeta.getSelectedItem() == "Perder turno") {
            tipo = 5;

        }
        if (tipoTarjeta.getSelectedItem() == "Salga de la cárcel") {
            tipo = 6;

        }
        if (tipoTarjeta.getSelectedItem() == "Vaya a la cárcel") {
            tipo = 7;

        }
        if (tipoTarjeta.getSelectedItem() == "Personalizada") {
            tipo = 8;
            jLabelCantidadCasillas.setVisible(true);
            txtCantidadCasillas.setVisible(true);
            jLabelCantidadMulta.setVisible(true);
            jLabelCantidadPremio.setVisible(true);
            txtCantidadMulta.setVisible(true);
            txtCantidadPremio.setVisible(true);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TipoTarjeta dialog = new TipoTarjeta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonHecho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCantidadCasillas;
    private javax.swing.JLabel jLabelCantidadMulta;
    private javax.swing.JLabel jLabelCantidadPremio;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMensaje;
    private javax.swing.JComboBox<String> tipoTarjeta;
    private javax.swing.JTextField txtCantidadCasillas;
    private javax.swing.JTextField txtCantidadMulta;
    private javax.swing.JTextField txtCantidadPremio;
    // End of variables declaration//GEN-END:variables
}
