/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Discover.Game.Casillas;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dany
 */
public class TipoCasilla extends javax.swing.JDialog {

    /**
     * Creates new form TipoCasilla
     */
    
    /**
     * crea un dialogo casilla
     * @param parent resive un parametro de tipo frame
     * @param modal recibe un boolean
     */
    public TipoCasilla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/img/iconoDiscover1.png")).getImage();
        setIconImage(icon);

        jLabelNombreCasilla.setVisible(false);
        txtNombreCasilla.setEnabled(false);
        jLabelcolor.setVisible(false);
        tipoColor.setVisible(false);
        jLabelPrecio.setVisible(false);
        txtPrecio.setVisible(false);
        jLabelPrecioEstancia.setVisible(false);
        txtPrecioEstancia.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNombreCasilla = new javax.swing.JTextField();
        jLabelNombreCasilla = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        tipoCasilla = new javax.swing.JComboBox<>();
        botonHecho = new javax.swing.JButton();
        jLabelcolor = new javax.swing.JLabel();
        tipoColor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        txtPrecioEstancia = new javax.swing.JTextField();
        jLabelPrecioEstancia = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoDiscover1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo Casilla - Discover");

        jPanel2.setBackground(new java.awt.Color(227, 0, 38));

        txtNombreCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCasillaActionPerformed(evt);
            }
        });
        txtNombreCasilla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNombreCasillaPropertyChange(evt);
            }
        });
        txtNombreCasilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreCasillaKeyPressed(evt);
            }
        });

        jLabelNombreCasilla.setForeground(java.awt.Color.white);
        jLabelNombreCasilla.setText("Nombre Casilla");

        jLabelTipo.setForeground(java.awt.Color.white);
        jLabelTipo.setText("Tipo");

        tipoCasilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Inicio", "Lugar", "Estacion", "Servicio", "Tomar Tarjeta", "Carcel", "Vacio", "Trampa" }));
        tipoCasilla.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                tipoCasillaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        tipoCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCasillaActionPerformed(evt);
            }
        });

        botonHecho.setText("Hecho");
        botonHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHechoActionPerformed(evt);
            }
        });

        jLabelcolor.setForeground(java.awt.Color.white);
        jLabelcolor.setText("Color");

        tipoColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Color", "Amarillo", "Azul", "Rojo", "Negro", "Cyan", "Gris", "Verde", "Magenta", "Rosado" }));
        tipoColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoColorActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoDiscover1.png"))); // NOI18N

        txtPrecio.setText("300");
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPrecioPropertyChange(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioKeyPressed(evt);
            }
        });

        jLabelPrecio.setForeground(java.awt.Color.white);
        jLabelPrecio.setText("Precio");

        txtPrecioEstancia.setText("50");
        txtPrecioEstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioEstanciaActionPerformed(evt);
            }
        });
        txtPrecioEstancia.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPrecioEstanciaPropertyChange(evt);
            }
        });
        txtPrecioEstancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioEstanciaKeyPressed(evt);
            }
        });

        jLabelPrecioEstancia.setForeground(java.awt.Color.white);
        jLabelPrecioEstancia.setText("Precio Estancia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabelPrecio)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNombreCasilla)
                        .addComponent(tipoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelcolor)
                        .addComponent(tipoCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTipo))
                    .addComponent(botonHecho, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelPrecioEstancia)
                    .addComponent(txtPrecioEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelNombreCasilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPrecioEstancia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(botonHecho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreCasillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCasillaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if ("".equals(txtNombreCasilla.getText())) {
                System.out.println("El JTextField está vacío");
                JOptionPane.showMessageDialog(this, "El JTextField está vacío");

            }

            setNombre(txtNombreCasilla.getText());
            JOptionPane.showMessageDialog(this, "Agregado con Exito");
            dispose();

        }
    }//GEN-LAST:event_txtNombreCasillaKeyPressed

    static int tipo, precio, precioEstancia;
    static String nombre;
    static Color color;

    public static int getTipo() {
        return tipo;
    }

    public static void setTipo(int tipo) {
        TipoCasilla.tipo = tipo;
    }

    public static String getNombre() {
        return nombre;
    }

    public static void setNombre(String nombre) {
        TipoCasilla.nombre = nombre;
    }

    public static Color getColor() {
        return color;
    }

    public static void setColor(Color color) {
        TipoCasilla.color = color;
    }

    public static int getPrecio() {
        return precio;
    }

    public static void setPrecio(int precio) {
        TipoCasilla.precio = precio;
    }

    public static int getPrecioEstancia() {
        return precioEstancia;
    }

    public static void setPrecioEstancia(int precioEstancia) {
        TipoCasilla.precioEstancia = precioEstancia;
    }

    /**
     * agrega a las variables lo que el usuario escribio en los campos
     *
     * @param evt
     */
    private void botonHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHechoActionPerformed
        if ("".equals(txtNombreCasilla.getText())) {
            System.out.println("El JTextField está vacío");
            JOptionPane.showMessageDialog(this, "El JTextField está vacío");
        }

        setNombre(txtNombreCasilla.getText());
        setPrecio(Integer.parseInt(txtPrecio.getText()));
        setPrecioEstancia(Integer.parseInt(txtPrecioEstancia.getText()));
        JOptionPane.showMessageDialog(this, "Agregado con Exito");
        dispose();
    }//GEN-LAST:event_botonHechoActionPerformed

    private void tipoCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCasillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCasillaActionPerformed

    private void tipoColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoColorActionPerformed

    private void txtNombreCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCasillaActionPerformed

    }//GEN-LAST:event_txtNombreCasillaActionPerformed
    /**
     * llama al metodo agregar
     *
     * @param evt
     */
    private void tipoCasillaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_tipoCasillaPopupMenuWillBecomeInvisible
        agregar();
    }//GEN-LAST:event_tipoCasillaPopupMenuWillBecomeInvisible

    private void txtNombreCasillaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNombreCasillaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCasillaPropertyChange

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPrecioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioPropertyChange

    private void txtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyPressed

    private void txtPrecioEstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioEstanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioEstanciaActionPerformed

    private void txtPrecioEstanciaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPrecioEstanciaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioEstanciaPropertyChange

    private void txtPrecioEstanciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioEstanciaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioEstanciaKeyPressed

    /**
     * agrega un valor a la variable tipo dependiendo de lo que se
     * sellecione en el jcombobox
     */
    public void agregar() {
        if (tipoCasilla.getSelectedItem() == "Inicio") {
            tipo = 0;
            jLabelNombreCasilla.setVisible(true);
            txtNombreCasilla.setText("Inicio");
            txtNombreCasilla.setEnabled(false);
            txtNombreCasilla.requestFocus();
            botonHecho.requestFocus();

            jLabelcolor.setVisible(false);
            tipoColor.setVisible(false);

        }
//        if (tipoCasilla.getSelectedItem() == "Propiedad") {
//            tipo = 1;
//            txtNombreCasilla.requestFocus();
//            jLabelNombreCasilla.setVisible(true);
//            txtNombreCasilla.setEnabled(true);
//            
//            jLabelcolor.setVisible(true);
//            tipoColor.setVisible(true);
//        }
        if (tipoCasilla.getSelectedItem() == "Lugar") {
            tipo = 2;
            txtNombreCasilla.requestFocus();
            jLabelNombreCasilla.setVisible(true);
            txtNombreCasilla.setEnabled(true);

            jLabelcolor.setVisible(true);
            tipoColor.setVisible(true);

            jLabelPrecio.setVisible(true);
            txtPrecio.setVisible(true);
            jLabelPrecioEstancia.setVisible(true);
            txtPrecioEstancia.setVisible(true);

        }
        if (tipoCasilla.getSelectedItem() == "Estacion") {
            tipo = 3;
            txtNombreCasilla.requestFocus();
            jLabelNombreCasilla.setVisible(true);
            txtNombreCasilla.setEnabled(true);

            jLabelcolor.setVisible(true);
            tipoColor.setVisible(true);

            jLabelPrecio.setVisible(true);
            txtPrecio.setVisible(true);
            jLabelPrecioEstancia.setVisible(true);
            txtPrecioEstancia.setVisible(true);

        }
        if (tipoCasilla.getSelectedItem() == "Servicio") {
            tipo = 4;
            txtNombreCasilla.requestFocus();
            jLabelNombreCasilla.setVisible(true);
            txtNombreCasilla.setEnabled(true);

            jLabelcolor.setVisible(true);
            tipoColor.setVisible(true);

            jLabelPrecio.setVisible(true);
            txtPrecio.setVisible(true);
            jLabelPrecioEstancia.setVisible(true);
            txtPrecioEstancia.setVisible(true);

        }
        if (tipoCasilla.getSelectedItem() == "Tomar Tarjeta") {
            tipo = 5;
            botonHecho.requestFocus();
            txtNombreCasilla.setText("Tomar Tarjeta");
            jLabelNombreCasilla.setVisible(false);
            txtNombreCasilla.setEnabled(false);

            jLabelcolor.setVisible(true);
            tipoColor.setVisible(true);

        }
        if (tipoCasilla.getSelectedItem() == "Carcel") {
            tipo = 6;
            botonHecho.requestFocus();
            txtNombreCasilla.setText("Carcel");
            jLabelNombreCasilla.setVisible(false);
            txtNombreCasilla.setEnabled(false);
            jLabelcolor.setVisible(false);
            tipoColor.setVisible(false);

        }
        if (tipoCasilla.getSelectedItem() == "Vacio") {
            tipo = 7;
            botonHecho.requestFocus();
            txtNombreCasilla.setText("");
            jLabelNombreCasilla.setVisible(false);
            txtNombreCasilla.setEnabled(false);
            jLabelcolor.setVisible(false);
            tipoColor.setVisible(false);

        }
        if (tipoCasilla.getSelectedItem() == "Trampa") {
            tipo = 8;

            botonHecho.requestFocus();
            txtNombreCasilla.setText("Trampa");
            jLabelNombreCasilla.setVisible(false);
            txtNombreCasilla.setEnabled(false);
            jLabelcolor.setVisible(false);
            tipoColor.setVisible(false);

        }
        obtenerColor();
    }
/**
 * sirve para settear el color dependiendo de lo elegido por el usuario en combobox
 */
    public void obtenerColor() {
        /*Color del jugador
        Amarillo
        Azul
        Rojo
        Negro
        Cyan
        Gris
        Verde
        Magenta
        Rosado*/

        if (tipoColor.getSelectedItem() == "Amarillo") {
            color = Color.YELLOW;
        }
        if (tipoColor.getSelectedItem() == "Azul") {
            color = Color.BLUE;
        }
        if (tipoColor.getSelectedItem() == "Rojo") {
            color = Color.RED;
        }
        if (tipoColor.getSelectedItem() == "Negro") {
            color = Color.BLACK;
        }
        if (tipoColor.getSelectedItem() == "Cyan") {
            color = Color.CYAN;
        }
        if (tipoColor.getSelectedItem() == "Gris") {
            color = Color.GRAY;
        }
        if (tipoColor.getSelectedItem() == "Verde") {
            color = Color.GREEN;
        }
        if (tipoColor.getSelectedItem() == "Magenta") {
            color = Color.MAGENTA;
        }
        if (tipoColor.getSelectedItem() == "Rosado") {
            color = Color.PINK;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoCasilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoCasilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoCasilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoCasilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TipoCasilla dialog = new TipoCasilla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonHecho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNombreCasilla;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecioEstancia;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelcolor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> tipoCasilla;
    private javax.swing.JComboBox<String> tipoColor;
    private javax.swing.JTextField txtNombreCasilla;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioEstancia;
    // End of variables declaration//GEN-END:variables
}
