/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Discover.GUI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author dany
 */
public class NuevoTablero extends javax.swing.JFrame {

    /**
     * Creates new form NuevoTablero
     */
    public NuevoTablero() {

        initComponents();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/img/iconoDiscover1.png")).getImage();
        setIconImage(icon);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtCantidadCasillas = new javax.swing.JTextField();
        labelCanCasillas = new javax.swing.JLabel();
        labelCantTarjetas = new javax.swing.JLabel();
        txtCantidadTarjetas = new javax.swing.JTextField();
        labelCanDineroInicial = new javax.swing.JLabel();
        txtCantidadDineroInical = new javax.swing.JTextField();
        labelCantDineroVuelta = new javax.swing.JLabel();
        txtCantidadDineroVuelta = new javax.swing.JTextField();
        labelCantCasasMax = new javax.swing.JLabel();
        txtCantidadCasasMax1 = new javax.swing.JTextField();
        txtCantidadHotelesMax = new javax.swing.JTextField();
        labelCantHotelesMax = new javax.swing.JLabel();
        jSliderCantidadDados = new javax.swing.JSlider();
        labelCantDados = new javax.swing.JLabel();
        jSliderCantidadJugadores = new javax.swing.JSlider();
        labelCantJugadoresMax = new javax.swing.JLabel();
        txtCantidadCasillas1 = new javax.swing.JTextField();
        labelCanCasillas1 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPorcentajeHipoteca = new javax.swing.JTextField();
        labelCantTarjetas1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Tablero");
        setName("nuevoTablero"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(227, 0, 38));

        txtCantidadCasillas.setText("12");
        txtCantidadCasillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadCasillasActionPerformed(evt);
            }
        });

        labelCanCasillas.setForeground(java.awt.Color.white);
        labelCanCasillas.setText("Cantidad casillas");

        labelCantTarjetas.setForeground(java.awt.Color.white);
        labelCantTarjetas.setText("Cantidad Tarjetas");

        txtCantidadTarjetas.setText("5");
        txtCantidadTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadTarjetasActionPerformed(evt);
            }
        });

        labelCanDineroInicial.setForeground(java.awt.Color.white);
        labelCanDineroInicial.setText("Cantidad de dinero Inicial");

        txtCantidadDineroInical.setText("5000");

        labelCantDineroVuelta.setForeground(java.awt.Color.white);
        labelCantDineroVuelta.setText("Cantidad de dinero por vuelta");

        txtCantidadDineroVuelta.setText("220");
        txtCantidadDineroVuelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadDineroVueltaActionPerformed(evt);
            }
        });

        labelCantCasasMax.setForeground(java.awt.Color.white);
        labelCantCasasMax.setText("Cantidad de casas Max. ");

        txtCantidadCasasMax1.setText("4");
        txtCantidadCasasMax1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadCasasMax1ActionPerformed(evt);
            }
        });

        txtCantidadHotelesMax.setText("4");

        labelCantHotelesMax.setForeground(java.awt.Color.white);
        labelCantHotelesMax.setText("Cantidad de hoteles Max. ");

        jSliderCantidadDados.setForeground(java.awt.Color.white);
        jSliderCantidadDados.setMajorTickSpacing(1);
        jSliderCantidadDados.setMaximum(3);
        jSliderCantidadDados.setMinimum(1);
        jSliderCantidadDados.setPaintLabels(true);
        jSliderCantidadDados.setPaintTicks(true);
        jSliderCantidadDados.setValue(2);
        jSliderCantidadDados.setBorder(null);
        jSliderCantidadDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelCantDados.setForeground(java.awt.Color.white);
        labelCantDados.setText("Cantidad de dados");

        jSliderCantidadJugadores.setForeground(java.awt.Color.white);
        jSliderCantidadJugadores.setMajorTickSpacing(1);
        jSliderCantidadJugadores.setMaximum(6);
        jSliderCantidadJugadores.setMinimum(2);
        jSliderCantidadJugadores.setPaintLabels(true);
        jSliderCantidadJugadores.setPaintTicks(true);
        jSliderCantidadJugadores.setValue(2);
        jSliderCantidadJugadores.setBorder(null);
        jSliderCantidadJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelCantJugadoresMax.setForeground(java.awt.Color.white);
        labelCantJugadoresMax.setText("Cantidad  de Juagadores Max.");

        txtCantidadCasillas1.setText("TableroDiscover");
        txtCantidadCasillas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadCasillas1ActionPerformed(evt);
            }
        });

        labelCanCasillas1.setForeground(java.awt.Color.white);
        labelCanCasillas1.setText("Nombre ");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoDiscover1.png"))); // NOI18N

        txtPorcentajeHipoteca.setText("12");
        txtPorcentajeHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeHipotecaActionPerformed(evt);
            }
        });

        labelCantTarjetas1.setForeground(java.awt.Color.white);
        labelCantTarjetas1.setText("Porcentaje sobre Hipoteca");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCanCasillas1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCantidadCasillas1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSliderCantidadDados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(labelCantDados, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelCantHotelesMax, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSliderCantidadJugadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(labelCantJugadoresMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidadHotelesMax, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelCantTarjetas1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPorcentajeHipoteca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelCanCasillas)
                                .addComponent(labelCantTarjetas)
                                .addComponent(txtCantidadTarjetas)
                                .addComponent(txtCantidadCasillas)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(labelCanDineroInicial)
                                .addComponent(txtCantidadDineroInical))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCantidadDineroVuelta)
                                .addComponent(labelCantDineroVuelta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelCantCasasMax)
                            .addComponent(txtCantidadCasasMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCanCasillas)
                        .addGap(9, 9, 9)
                        .addComponent(txtCantidadCasillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCantTarjetas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCanCasillas1)
                        .addGap(9, 9, 9)
                        .addComponent(txtCantidadCasillas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelCantTarjetas1)
                        .addGap(9, 9, 9)
                        .addComponent(txtPorcentajeHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCanDineroInicial)
                        .addGap(12, 12, 12)
                        .addComponent(txtCantidadDineroInical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCantDineroVuelta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidadDineroVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCantCasasMax)
                        .addGap(12, 12, 12)
                        .addComponent(txtCantidadCasasMax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCantJugadoresMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderCantidadJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(labelCantDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderCantidadDados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCantHotelesMax)
                        .addGap(12, 12, 12)
                        .addComponent(txtCantidadHotelesMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static public int cantidadCasillas;
    static public int cantidadCasillasUsuario = (cantidadCasillas * 4) - 2;
    static public int cantidadDados;
    static public int cantidadCasas;
    static public int cantidadHoteles;
    static public int cantidadJugadores;
    static public int cantidadDineroInicial;
    static public int cantidadDineroVuelta;
    static public int cantidadTarjetas;
    static public int porcentajeHipoteca;

/**
 * guardo los datos proporcionados por el usuario en las variable correspondientes 
 * @param evt 
 */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        cantidadCasillas = (Integer.parseInt(txtCantidadCasillas.getText()));
        cantidadDados = jSliderCantidadDados.getValue();
        cantidadJugadores = jSliderCantidadJugadores.getValue();
        cantidadCasas = Integer.parseInt(txtCantidadCasasMax1.getText());
        cantidadHoteles = Integer.parseInt(txtCantidadHotelesMax.getText());
        cantidadDineroInicial = Integer.parseInt(txtCantidadDineroInical.getText());
        cantidadDineroVuelta = Integer.parseInt(txtCantidadDineroVuelta.getText());
        cantidadTarjetas=Integer.parseInt(txtCantidadTarjetas.getText());
        porcentajeHipoteca=Integer.parseInt(txtPorcentajeHipoteca.getText());
        dispose();

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();

    }//GEN-LAST:event_botonCancelarActionPerformed

    private void txtCantidadDineroVueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadDineroVueltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadDineroVueltaActionPerformed

    private void txtCantidadCasillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadCasillasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCasillasActionPerformed

    private void txtCantidadTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadTarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadTarjetasActionPerformed

    private void txtCantidadCasillas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadCasillas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCasillas1ActionPerformed

    private void txtPorcentajeHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeHipotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeHipotecaActionPerformed

    private void txtCantidadCasasMax1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadCasasMax1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCasasMax1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSliderCantidadDados;
    private javax.swing.JSlider jSliderCantidadJugadores;
    private javax.swing.JLabel labelCanCasillas;
    private javax.swing.JLabel labelCanCasillas1;
    private javax.swing.JLabel labelCanDineroInicial;
    private javax.swing.JLabel labelCantCasasMax;
    private javax.swing.JLabel labelCantDados;
    private javax.swing.JLabel labelCantDineroVuelta;
    private javax.swing.JLabel labelCantHotelesMax;
    private javax.swing.JLabel labelCantJugadoresMax;
    private javax.swing.JLabel labelCantTarjetas;
    private javax.swing.JLabel labelCantTarjetas1;
    private javax.swing.JTextField txtCantidadCasasMax1;
    private javax.swing.JTextField txtCantidadCasillas;
    private javax.swing.JTextField txtCantidadCasillas1;
    private javax.swing.JTextField txtCantidadDineroInical;
    private javax.swing.JTextField txtCantidadDineroVuelta;
    private javax.swing.JTextField txtCantidadHotelesMax;
    private javax.swing.JTextField txtCantidadTarjetas;
    private javax.swing.JTextField txtPorcentajeHipoteca;
    // End of variables declaration//GEN-END:variables
}
