/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Discover.GUI;

import static Discover.Game.Casillas.TipoCasilla.setNombre;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author dany
 */
public class TipoJugador extends javax.swing.JDialog {

    /**
     * Creates new form TipoJugador
     */
       /**
     * crea un dialogo 
     * @param parent resive un parametro de tipo frame
     * @param modal recibe un boolean
     */
    public TipoJugador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoColor = new javax.swing.JComboBox<>();
        jLabelcolor = new javax.swing.JLabel();
        jButtonHecho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo Jugador - Discover");

        tipoColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color del jugador", "Amarillo", "Azul", "Rojo", "Negro", "Cyan", "Gris", "Verde", "Magenta", "Rosado" }));
        tipoColor.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                tipoColorPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        tipoColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoColorActionPerformed(evt);
            }
        });

        jLabelcolor.setText("Color");

        jButtonHecho.setText("Hecho");
        jButtonHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHechoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tipoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcolor)
                    .addComponent(jButtonHecho))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelcolor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButtonHecho)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoColorActionPerformed
    static Color jugadorColor;

    public static Color getJugadorColor() {
        return jugadorColor;
    }

    public static void setJugadorColor(Color jugadorColor) {
        TipoJugador.jugadorColor = jugadorColor;
    }
/**
 * sirve para settear el color dependiendo de lo elegido por el usuario en combobox
 */
    public void agregar() {
        /*
        Colores
    ---------------
        Amarillo
        Azul
        Rojo
        Negro
        Cyan
        Gris
        Verde
        Magenta
        Rosado
         */
        if (tipoColor.getSelectedItem() == "Amarillo") {
            setJugadorColor(Color.YELLOW);

        }
        if (tipoColor.getSelectedItem() == "Azul") {
            setJugadorColor(Color.BLUE);

        }
        if (tipoColor.getSelectedItem() == "Rojo") {
            setJugadorColor(Color.RED);

        }
        if (tipoColor.getSelectedItem() == "Negro") {
            setJugadorColor(Color.BLACK);

        }
        if (tipoColor.getSelectedItem() == "Cyan") {
            setJugadorColor(Color.CYAN);

        }
        if (tipoColor.getSelectedItem() == "Gris") {
            setJugadorColor(Color.GRAY);

        }
        if (tipoColor.getSelectedItem() == "Verde") {
            setJugadorColor(Color.GREEN);

        }
        if (tipoColor.getSelectedItem() == "Magenta") {
            setJugadorColor(Color.MAGENTA);

        }
        if (tipoColor.getSelectedItem() == "Rosado") {
            setJugadorColor(Color.PINK);

        }

    }

    private void jButtonHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHechoActionPerformed
        JOptionPane.showMessageDialog(this, "Agregado con Exito");
        dispose();
    }//GEN-LAST:event_jButtonHechoActionPerformed

    private void tipoColorPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_tipoColorPopupMenuWillBecomeInvisible
agregar();
    }//GEN-LAST:event_tipoColorPopupMenuWillBecomeInvisible

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHecho;
    private javax.swing.JLabel jLabelcolor;
    private javax.swing.JComboBox<String> tipoColor;
    // End of variables declaration//GEN-END:variables
}
